require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "db/migrate/**/*"
    - "config/**/*"
    - "Gemfile"
    - "Rakefile"
    - "config.ru"
    - "vendor/**/*"
    - "node_modules/**/*"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "config/**/*"

Layout/LineLength:
  Max: 120
  Exclude:
    - "spec/**/*"

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleMemoizedHelpers:
  Max: 10

Rails/SkipsModelValidations:
  Exclude:
    - "app/jobs/archive_expired_games_job.rb"
